### ISSUE TITLE
Payout Customization

### ISSUE THREAD

**Issue by Rystyles** [ExcessiveAmountsOfZombies/Professions#1]
Hello! First of all I want to say I love the mod and all the work that was put into it!

I was wondering however, if it were possible for pack creators to change the payout options for certain professions. For example instead of the EnderDragon giving the player $600, I could theoretically make it so that it gave the player $100 instead. I've tried to make these changes myself within the mod's files, however when doing so, the mod will either delete itself from my custom modpack or the mod will simply brick and no professions will be selectable from the professions screen.

Of course if this is not possible to customize, I understand, but I thought I would ask regardless.

Thank you!

**Comment by ExcessiveAmountsOfZombies** [comment]
it sure is, you'll have to copy the professions from [here](https://github.com/ExcessiveAmountsOfZombies/Professions/tree/main/fabric/src/main/generated/resourcepacks/defaults/data/professions/professions/occupations) into your own data pack, disable the 'usebuiltindatapacks' option in the config so it won't load the defaults and then just change the values you'd like to change. 

If doing it this way doesn't work I could look at your logs to get an idea of where things might be going wrong.

Glad you like the mod! there are many more features coming soon!

**Comment by Rystyles** [comment]
Awesome! Thank you so much! I was able to make the modifications successfully.

**Comment by ExcessiveAmountsOfZombies** [comment]
Glad to help 😄
