### ISSUE TITLE
[Forge] Incompatibility with Inventory Weight ON SERVERS

### ISSUE THREAD

**Issue by Pingu-Pox** [ExcessiveAmountsOfZombies/Professions#10]
From Creative Mode:
Console log: https://paste.ee/p/x4XA8
Crash log: [crash-2022-10-06_18.55.29-client.txt](https://github.com/ExcessiveAmountsOfZombies/Professions/files/9729516/crash-2022-10-06_18.55.29-client.txt)

From Survival Mode:
Console log: https://paste.ee/p/u9bci
Crash log: [crash-2022-10-06_19.29.53-client.txt](https://github.com/ExcessiveAmountsOfZombies/Professions/files/9729515/crash-2022-10-06_19.29.53-client.txt)

Describe the bug
Mousing-over an item in your inventory causes a CTD.

To Reproduce
Make a 1.18.2 Minecraft instance with FML 40.1.80, make a matching server.
Add the following mods (all are latest versions, default configs):
Professions-1.18.2-FORGE-1.0.0-all
inventory_weight-1.2.jar

Start game, log into server, mouse over an item in your inventory, CTD.

Expected behavior
Should be able to mouse over items and not have a crash.

Professions: https://www.curseforge.com/minecraft/mc-mods/professions
Inventory Weight: https://www.curseforge.com/minecraft/mc-mods/inventory-weight

**Comment by ExcessiveAmountsOfZombies** [comment]
should be fixed in a future version
