### ISSUE TITLE
Client crash when opening inventory [FORGE 1.19.2 - 1.0.2]

### ISSUE THREAD

**Issue by gefailter71** [ExcessiveAmountsOfZombies/Professions#12]
Professions Version: 1.19.2 Forge 1.0.2 all, tested it with 1.0.3 as well doesnt work
Forge Version 43.1.47

I have Professions both on the server and client and when I try to open my inventory it kills my client. 
When removing it from the Client it works fine.

Latest log is attached. 
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Professions/files/9891451/latest.log)

**Comment by koder1337** [comment]
Same issue, but I the reason of this issue is :

java.lang.NullPointerException: Cannot invoke "com.epherical.professions.PlayerManager.getPlayer(java.util.UUID)" because the return value of "com.epherical.professions.CommonPlatform.getPlayerManager()" is null
