### ISSUE TITLE
Crash when starting the server after updating Professions

### ISSUE THREAD

**Issue by sirben99** [ExcessiveAmountsOfZombies/Professions#3]
Hey!

I have a problem where after updating Professions to 0.3.0 my server crashes. Downgrading to 0.2.4 fixes the issue, no crash occurs.

Crash report dint generate, but the error is at the bottom of the log.

Mod Version: Pofessions-1.18.2-FABRIC-0.3.0

Log:
[logs_latest (3).log](https://github.com/ExcessiveAmountsOfZombies/Professions/files/9227067/logs_latest.3.log)

If you need anything else please let me know!

Ben

**Comment by ExcessiveAmountsOfZombies** [comment]
kinda figured this would happen, luckily 0.3.0 doesn't change anything except for add the new screen. i'll have a fix soon

**Comment by ExcessiveAmountsOfZombies** [comment]
0.3.1 is out now and fixes this issue
