### ISSUE TITLE
Command Reward option

### ISSUE THREAD

**Issue by ClockwerkKaiser** [ExcessiveAmountsOfZombies/Professions#4]
After years of creating and maintaining a spigot server with custom professions plugins, I've recently decided to create a fabric modpack utilizing this mod. Things are going great so far. However, I find myself wishing there was an option to run a command as a reward for completing profession tasks. As a part of this, a built-in placeholder for the target player might also be a good idea. 

Various examples for how useful this would be: 

- Modpack Creators using Numismatic Overhaul can use NO's command to directly add currency to the player's balance (thus avoiding missed item reward drops and inventory clutter). 

- Modpack Creators using PlayerEx could grant levels / skill point as rewards for configured tasks. 

- Modpack Creators using Minecraft Comes Alive Reborn could increment / decrement reputation hearts with nearby villagers upon completing configured tasks

Command rewards would be extremely powerful and useful IMO. 

Thank you for you consideration.

**Comment by ExcessiveAmountsOfZombies** [comment]
I was thinking that when I start working on the perks/milestone system that commands would be a good fit here. was also planning on making an addon to add actions/rewards for as many mods as I can think of, numismatic especially, but also for mods like tech reborn, and anything else that could make for repetitive actions.

not really any way you could've known that, as I don't really have a planned feature list, but it is planned!

**Comment by ExcessiveAmountsOfZombies** [comment]
Ok i'm uploading 0.3.5 right now and it includes this new milestone system. It only has the one command option right now.
if you have custom professions you'll want to add at the very least this to the datapack
![image](https://user-images.githubusercontent.com/30448663/187044644-82754f3c-1745-4948-a4ed-0816f33acd05.png)

if you want to add milestones, here is the one.
![image](https://user-images.githubusercontent.com/30448663/187044667-4e970962-9f82-4622-8817-1e05723c4dbe.png)
