### ISSUE TITLE
0.3.2 - 1.18.2 - FABRIC - Crash on world creation (cardinal-components)

### ISSUE THREAD

**Issue by Bob74** [ExcessiveAmountsOfZombies/Professions#7]
Hi!

I'm having a crash at world creation which seems to come from cardinal-components:

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/23/22, 9:27 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'dev.onyxstudios.cca.api.v3.component.ComponentProvider dev.onyxstudios.cca.api.v3.component.ComponentProvider.fromLevel(net.minecraft.class_5217)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
	at net.minecraft.server.MinecraftServer.handler$zfl000$onEndTick(MinecraftServer:1801)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:889)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
```

According to [this issue](https://github.com/OnyxStudios/Cardinal-Components-API/issues/125) with another mod, the embedded version of cardinal-components (5.0.1) is too high and not compatible with 1.18.2

I removed the jar from META-INF and added cardinal-components 4.2.0 to my mods folder and the game doesn't crash anymore :)

**Comment by ExcessiveAmountsOfZombies** [comment]
I mean I don't mean to contradict the person who wrote cardinal components but...
![image](https://user-images.githubusercontent.com/30448663/186285226-1b2d70cb-988b-44e2-b282-37e7134e951e.png)
and then i ran around the world and logged out, twice

 The jars I include in professions don't even indicate that the version is too high, the fabric.mod.json says it supports >=1.17

might need a mod list or something, no idea whats happening

**Comment by Bob74** [comment]
You are right, the problem is coming from another mod embedding cardinal 4.0.1.
I don't really know how it causes this crash but that's on me now

Thanks for your help!
