### ISSUE TITLE
[Forge] Incompatibility with Tetra

### ISSUE THREAD

**Issue by Pingu-Pox** [ExcessiveAmountsOfZombies/Professions#8]
Console log: https://paste.ee/p/jC1MN
Crash log: [crash-2022-08-30_16.03.26-fml.txt](https://github.com/ExcessiveAmountsOfZombies/Professions/files/9456684/crash-2022-08-30_16.03.26-fml.txt)

**Describe the bug**
Minecraft fails to finish loading up, and gets the "error loading mods 1 error has occurred during loading" screen.

**To Reproduce**
1. Make a 1.18.2 Minecraft instance with FML 40.1.74
2. Add the following mods (all are latest versions):
- tetra-1.18.2-4.9.3.jar
- mutil-1.18.2-4.5.0.jar (tetra's dependency)
- Professions-1.18.2-FORGE-0.3.2-all.jar
3. Start game, before the main menu is reached, error screen is displayed

**Expected behavior**
Game loads, and works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/21115660/187543210-1741cc2a-7352-4b9a-aea2-2f679feef4ac.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm going to archive this version of professions until the mod has more features. it's actually almost done, probably just a couple more weeks and then perks/milestones will be complete.

Rather than an incompatibility I think I just messed up and uploaded a version with an improper mixin refmap, and that causes tetra to fail on something later

**Comment by ExcessiveAmountsOfZombies** [comment]
ok, i'm uploading a new alpha https://www.curseforge.com/minecraft/mc-mods/professions/files/3984724 will have the issue fixed. might be the last alpha too. just need to make a better default datapack

**Comment by Pingu-Pox** [comment]
Looks good, thank you! Would it be possible to change the "currency" in a new datapack to use items instead of "eights_economy:dollars"?

**Comment by Pingu-Pox** [comment]
Thank you!
