### ISSUE TITLE
[Crash] Professions-1.18.2-FABRIC-0.3.5

### ISSUE THREAD

**Issue by withvoidwithin** [ExcessiveAmountsOfZombies/Professions#9]
[crash-2022-09-01_16.58.17-server.txt](https://github.com/ExcessiveAmountsOfZombies/Professions/files/9468957/crash-2022-09-01_16.58.17-server.txt)

**Comment by MeLikeChoco** [comment]
I believe the problem is 1.18.2's version is built against 1.19.2's version of Cardinal Components causing a problem. Probably have to fall back to a version with the correct version. The last working version should be "Professions-1.18.2-FABRIC-0.3.1.jar".

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading a fix now
